export const USER_LOGIN = "USER_LOGIN"
export type USER_LOGIN = typeof USER_LOGIN

export const USER_LOGOUT = "USER_LOGOUT"
export type USER_LOGOUT = typeof USER_LOGOUT

export const LOCALE_UPDATE = "LOCALE_UPDATE"
export type LOCALE_UPDATE = typeof LOCALE_UPDATE

export const DISPLAYED_ROUTE_UPDATE = "DISPLAYED_ROUTE_UPDATE";
export type DISPLAYED_ROUTE_UPDATE = typeof DISPLAYED_ROUTE_UPDATE;